# Generated by Django 4.2.5 on 2023-10-04 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDTO',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Nome do Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Produto')),
                ('description', models.TextField(verbose_name='Descrição do Produto')),
                ('inStock', models.BooleanField()),
                ('quantity', models.IntegerField(verbose_name='Quantidade Disponível do Produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInputDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5, 'Nome deve conter no minimo 5 caracteres.')], verbose_name='Nome do Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Preço minimo do produto deve ser 0,01.')], verbose_name='Preço do Produto')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Descrição deve conter no minimo 10 caracteres.')], verbose_name='Descrição do Produto')),
                ('inStock', models.BooleanField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Quantidade deve ser de no minimo 0.')], verbose_name='Quantidade Disponível do Produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUpdateDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(5, 'Nome deve conter no minimo 5 caracteres.')], verbose_name='Nome do Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Preço minimo do produto deve ser 0,01.')], verbose_name='Preço do Produto')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Descrição deve conter no minimo 10 caracteres.')], verbose_name='Descrição do Produto')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Quantidade deve ser de no minimo 0.')], verbose_name='Quantidade Disponível do Produto')),
            ],
        ),
    ]
